# Generated by Django 4.0.6 on 2022-09-06 02:35

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumno', verbose_name='Foto 4x4')),
                ('legajo', ckeditor.fields.RichTextField(help_text='Puede describir Altas, Bajas, Documentación, ect.')),
                ('baja', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Carrera')),
                ('abreviatura', models.CharField(max_length=4, unique=True)),
                ('legal', models.CharField(max_length=100, verbose_name='Resolución Oficial')),
                ('fecha_inicio', models.DateField()),
                ('duracion', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Año Duración')),
                ('cuatrimestre', models.IntegerField(default=1, verbose_name='Cantidad de Cuatrimestres')),
                ('tipo', models.CharField(choices=[('Tecnicatura', 'Tecnicatura'), ('Profesorado', 'Profesorado'), ('Licenciatura', 'Licenciatura'), ('PostGrado', 'PostGrado'), ('Curso', 'Curso'), ('Seminario', 'Seminario'), ('Otro', 'Otro')], default='Tec', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Cuota Enero', max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descuento', models.BooleanField(default=False, help_text='Es un descuento [Si - No]')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80, null=True)),
                ('horas_catedras', models.CharField(max_length=100)),
                ('legajo', ckeditor.fields.RichTextField(help_text='Puede describir Altas, Bajas, Titulos, ect.')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docente', verbose_name='Foto 4x4')),
                ('carreras', models.ManyToManyField(to='secretaria.carrera')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['persona'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=200)),
                ('mision', ckeditor.fields.RichTextField()),
                ('vision', ckeditor.fields.RichTextField()),
                ('facebook', models.CharField(blank=True, max_length=254, null=True)),
                ('instagram', models.CharField(blank=True, max_length=254, null=True)),
                ('twitter', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de Materia')),
                ('tipo', models.CharField(choices=[('A', 'Anual'), ('C', 'Cuatrimestral'), ('O', 'Otra')], default='C', max_length=1)),
                ('anio', models.CharField(choices=[('1', '1 Año'), ('2', '2 Año'), ('3', '3 Año'), ('4', '4 Año'), ('5', '5 Año'), ('6', '6 Año')], default='1', max_length=2, verbose_name='Año')),
                ('cuatrimestre', models.CharField(choices=[('1', '1 Cuat.'), ('2', '2 Cuat.'), ('3', '3 Cuat.'), ('4', '4 Cuat.'), ('5', '5 Cuat.'), ('6', '6 Cuat.'), ('7', '7 Cuat.'), ('8', '8 Cuat.')], default='1', max_length=2)),
                ('carrera_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('habilitada', models.BooleanField(default=False)),
                ('inicia', models.DateField()),
                ('cierra', models.DateField()),
                ('llamados', models.CharField(choices=[('Uno', 'Uno'), ('Dos', 'Dos'), ('Tres', 'Tres')], default='Dos', max_length=4, verbose_name='Cantidad de llamados')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('carreras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.carrera')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MesaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha1', models.DateField()),
                ('fecha2', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField()),
                ('materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.materia')),
                ('mesas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.mesa')),
            ],
            options={
                'verbose_name': 'Mesa Detalle',
                'ordering': ['fecha1', 'materias'],
            },
        ),
        migrations.CreateModel(
            name='MotivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Motivo de Baja')),
            ],
            options={
                'verbose_name': 'Motivo de Baja',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rendido', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.alumno')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.carrera')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoridad', models.CharField(choices=[('Titular', 'Titular'), ('Vocal 1', 'Vocal 1'), ('Vocal 2', 'Vocal 2'), ('Suplente', 'Suplente')], default='Vocal 1', max_length=8)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.docente')),
                ('mesadetalles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.mesadetalle')),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunales',
                'ordering': ['mesadetalles'],
            },
        ),
        migrations.CreateModel(
            name='Recibor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(choices=[('1', '1 Año'), ('2', '2 Año'), ('3', '3 Año'), ('4', '4 Año'), ('5', '5 Año'), ('6', '6 Año')], default='1 Año', max_length=5, verbose_name='Año Cursado')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Junio', max_length=10, verbose_name='Mes')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.concepto')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.recibo')),
            ],
            options={
                'verbose_name': 'Recibo Detalle',
                'verbose_name_plural': 'Recibos Detalles',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='D.N.I.')),
                ('apellido', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('fechanac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='Otro', max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.CharField(max_length=150)),
                ('vive', models.BooleanField(default=True)),
                ('baja', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.estadocivil')),
                ('motivo_baja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.motivobaja')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=200)),
                ('carga_horaria', models.CharField(max_length=100)),
                ('legajo', ckeditor.fields.RichTextField(help_text='Puede describir Altas, Bajas, Titulos, ect.')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='secretaria', verbose_name='Foto 4x4')),
                ('cargo', models.ManyToManyField(to='secretaria.cargo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.persona')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.persona'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='motivo_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.motivobaja'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.persona'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
