# Generated by Django 4.0.6 on 2022-09-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='baja',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='motivo_baja',
        ),
        migrations.AddField(
            model_name='docente',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='motivo_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.motivobaja'),
        ),
    ]
