# Generated by Django 4.0.6 on 2022-09-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibor',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Junio', max_length=10, verbose_name='Mes'),
        ),
    ]
