# Generated by Django 4.0.6 on 2022-09-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_remove_persona_baja_remove_persona_motivo_baja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='carreras',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleado', verbose_name='Foto 4x4'),
        ),
    ]
