# Generated by Django 4.0.6 on 2022-10-13 03:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secretaria', '0003_remove_docente_carreras_alter_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='docente/', verbose_name='Foto 4x4'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='legajo',
            field=ckeditor.fields.RichTextField(help_text='Puede describir Altas, Bajas, Ausentes, ect.'),
        ),
    ]
