# Generated by Django 4.2 on 2023-04-20 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_docente_usuario_alter_docente_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretaria.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechanac',
            field=models.DateField(help_text='formato de fecha: YYYY-MM-DD', verbose_name='Fecha de Nacimiento'),
        ),
    ]
