# Generated by Django 4.2 on 2023-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_alter_docente_persona_alter_persona_fechanac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='foto',
        ),
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='persona/', verbose_name='Foto 4x4'),
        ),
    ]
