# Generated by Django 4.2 on 2023-05-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_remove_alumno_foto_remove_docente_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretaria.persona', unique=True),
        ),
    ]
