# Generated by Django 4.2 on 2023-06-11 21:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_alter_docente_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretaria.persona'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='legajo',
            field=ckeditor.fields.RichTextField(help_text='Puedes Registrar: Altas, Bajas, Titulos, Ausentismo, ect.'),
        ),
    ]
